<?php  $this->headTitle()->append('Cliente');?>
<br /><br />
<a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'logout', 'module' => 'admin'), '', true); ?>">
	Logout </a>
<br>
Bem Vindo <?=$this->usuario->_fullName;?>
	<div align="center">
<table class="center" border="1">
<tr>
<th>Modelo</th>
<th>Marca</th>
<th>Estado</th>
<th>Cor</th>
<th>Preço</th>
<th>Visualização</th>
<th>Selecionar<br> modalidade de serviço</th>
</tr>
<?php 
foreach ($this->veiculos as $veiculo):
	?>
	<tr>
<td><?php echo $this->escape($veiculo['Modelo']);?></td>
<td><?php echo $this->escape($veiculo['Marca']);?></td>
<td><?php echo $this->escape($veiculo['Sigla']);?></td>
<td><?php echo $this->escape($veiculo['Cor']);?></td>
<td>R$ <?php echo $this->escape($veiculo['Preco']);?>,00</td>
<td><img src='<?php echo'/sga/public/imagem/'. $this->escape($veiculo['Foto']);?>' width="80"></td>
<td><a href="<?php echo $this->url(array('controller'=>'venda',
'action'=>'alugar', 'veiculo'=>$veiculo['Id_Veiculo'], 'modalidade'=>'1'));?>">Alugar</a>
<a href="<?php echo $this->url(array('controller'=>'venda',
'action'=>'vender', 'veiculo'=>$veiculo['Id_Veiculo'], 'modalidade'=>'2'));?>">Comprar</a></td>

</tr>
<?php 
endforeach;?> 
</table>
</div>