<?php echo $this->doctype();?>
<html xmlns="http://www.w3c.org/1999/xmlns">
<head>
<meta http-equiv="Content-type" content="text/html ; charset=UTF-8" />
<?php echo $this->headTitle()?>
<?php echo $this->headLink()?>
</head><body>

<?php 
$role = Zend_Auth::getInstance()->getIdentity()->_roleId;
if($role == 'Cliente'){
echo "<div align='center'><h1>Menu Cliente</h1></div>";
}else if($role == 'Administrador'){
echo "<div align='center'><h1>Menu Administrativo</h1></div>";
}else if($role == 'Gerente'){
echo "<div align='center'><h1>Menu do Gerente</h1></div>";
}else if($role == 'Vendedor'){
echo "<div align='center'><h1>Menu do Vendedor</h1></div>";
}
?>

<?php echo $this->layout()->content; ?>
</body>
</html>